gallery:
  source: _images
  tags:
    - tag1
    - tag2

markdown: kramdown
theme: minima
plugins:
  - jekyll-gallery-generator
baseurl: "/touren" # Wenn die Seite in einem Unterverzeichnis liegt, andernfalls leer lassen
url: "https://christoph4711.github.io"
