plugins:
  - jekyll-gallery-generator

gallery:
  base_path: /images
  output_dir: /gallery

markdown: kramdown
theme: minima
plugins:
  - jekyll-gallery-generator
baseurl: "/touren" # Wenn die Seite in einem Unterverzeichnis liegt, andernfalls leer lassen
url: "https://christoph4711.github.io"
