name: Jekyll Site CI

on:
  push:
    branches:
      - main  # Stelle sicher, dass dies der Branch ist, auf den du pusht
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install Dependencies
      run: |
        gem install jekyll
        bundle install

    - name: Build Jekyll Site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./_site
